### ISSUE TITLE
tor_: is particular stem version required?

### ISSUE THREAD

**Issue by mehturt** [munin-monitoring/contrib#1166]
Hello, is particular stem library version required to run this plugin?
I'm trying to run it on Debian stable box, but I'm getting error:

```
# munin-run tor_traffic autoconf
no (failed to import the required python module "GeoIP": No module named 'GeoIP')
Traceback (most recent call last):
  File "/etc/munin/plugins/tor_traffic", line 175, in autoconf
    with gen_controller() as controller:
  File "/etc/munin/plugins/tor_traffic", line 127, in gen_controller
    return stem.control.Controller.from_port(port=int(os.environ.get('torport',
NameError: name 'stem' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/etc/munin/plugins/tor_traffic", line 555, in <module>
    main()
  File "/etc/munin/plugins/tor_traffic", line 519, in main
    TorPlugin.autoconf()
  File "/etc/munin/plugins/tor_traffic", line 182, in autoconf
    except stem.connection:
AttributeError: module 'stem' has no attribute 'connection'
```

**Comment by sumpfralle** [comment]
Thank you for raising this issue. It should be fixed now.

**Comment by msebald** [comment]
Unfortunately I still get the same error with the fixed version:

```
munin-run tor_traffic

Traceback (most recent call last):
  File "/etc/munin/plugins/tor_traffic", line 550, in <module>
    main()
  File "/etc/munin/plugins/tor_traffic", line 543, in main
    provider.fetch()
  File "/etc/munin/plugins/tor_traffic", line 481, in fetch
    with gen_controller() as controller:
  File "/etc/munin/plugins/tor_traffic", line 127, in gen_controller
    return stem.control.Controller.from_port(port=int(os.environ.get('torport',
NameError: name 'stem' is not defined
```

**Comment by sumpfralle** [comment]
Indeed, the `autoconf` was fixed, but `fetch` still failed non-nicely. This is fixed now in 179f04721a59d379baadbd6cfe5418fe939cb03f.

Thanks for reporting back!

**Comment by sellwanger** [comment]
Where can i find this commit?

**Comment by sumpfralle** [comment]
I was sure, I uploaded it before. Now it is there ...

**Comment by sellwanger** [comment]
Thanks ;)
